######################################################################
# Automatically generated by qmake (2.01a) ? 6? 21 21:40:45 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
